version: '3'
services:
  dev:
    container_name: uavcast-dev
    user: uavcast
    privileged: true
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    restart: always
    volumes:
      - .:/app/uavcast:cached
      - uavdata:/app/uavcast/data
      - /var/lib/zerotier-one:/var/lib/zerotier-one:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev:ro
    ports:
      - '3000:3000'
      - '80:80'
    entrypoint:
      - '/bin/systemctl'
    # command: /bin/sh -c "while sleep 1000; do :; done"
    # tty: true
    # stdin_open: true
volumes:
  uavdata:
