version: '3.4'
services:
  dev:
    container_name: uavcast-dev
    user: uavcast
    privileged: true
    network_mode: host
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    restart: always
    volumes:
      - .:/app/uavcast:cached
      - uavdata:/app/uavcast/data
      - /var/lib/zerotier-one:/var/lib/zerotier-one
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev:ro
    entrypoint:
      - '/bin/systemctl'
volumes:
  uavdata:
