export const firmware: any = {
  0: 'Generic autopilot',
  1: 'Reserved',
  2: 'autopilot',
  3: 'ArduPilot',
  4: 'OpenPilot',
  5: 'Generic autopilot',
  6: 'Generic autopilot',
  7: 'Generic autopilot',
  8: 'No valid autopilot',
  9: 'PPZ UAV',
  10: 'UAV Dev Board',
  11: 'FlexiPilot',
  12: 'PX4 Autopilot',
  13: 'SMACCMPilot',
  14: 'AutoQuad',
  15: 'Armazila',
  16: 'Aerob',
  17: 'ASLUAV autopilot',
  18: 'SmartAP Autopilot',
  19: 'AirRails',
};