export const frame: any = {
  0: 'Generic micro air vehicle',
  1: 'Fixed wing',
  2: 'Quadrotor',
  3: 'Coaxial helicopter',
  4: 'Helicopter With Tail R',
  5: 'Ground installation',
  6: 'GCS',
  7: 'Airship, controlled',
  8: 'Free balloon',
  9: 'Rocket',
  10: 'Ground rover',
  11: 'Surface vessel',
  12: 'Submarine',
  13: 'Hexarotor',
  14: 'Octorotor',
  15: 'Tricopter',
  16: 'Flapping wing',
  17: 'Kite',
  18: 'Companion',
  19: 'Two-rotor VTOL',
  20: 'Quad-rotor VTOL',
  21: 'Tiltrotor VTOL',
  22: 'VTOL reserved 2',
  23: 'VTOL reserved 3',
  24: 'VTOL reserved 4',
  25: 'VTOL reserved 5',
  26: 'Gimbal',
  27: 'ADSB system',
  28: 'Steerable, nonrigid airfoil',
  29: 'Dodecarotor',
  30: 'Camera',
  31: 'Charging station',
  32: 'FLARM collision avoidance system',
  33: 'Servo',
};
