## GCC
FROM --platform=$TARGETPLATFORM gcc:9.2 as gcc
ARG TARGETPLATFORM
ARG BUILDPLATFORM
WORKDIR /gcc

# install app dependencies
COPY ["bin", "./"]

RUN apt-get update && apt-get install -y \
                   libcppunit-dev \
                   libjsoncpp-dev \
                   libv4l-dev \
                   libgstreamer1.0-dev \
                   libcurl4-nss-dev \
                   sqlite3 \
                   libsqlite3-dev
RUN mkdir -p build
RUN make
ENTRYPOINT ["tail", "-f", "/dev/null"]