FROM sinamics/debian-uavcast-base:latest
LABEL maintainer="Bernt Christian Egeland / (aka sinamics)"

WORKDIR /app/uavcast

ENV NPM_CONFIG_PREFIX=/home/uavcast/.npm-global
ENV PATH=$PATH:/home/uavcast/.npm-global/bin

ARG USERNAME=uavcast
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

RUN sudo usermod -a -G docker uavcast

RUN apt-get update && apt-get install -y \
                   libcppunit-dev \
                   libjsoncpp-dev \
                   libv4l-dev \
                   libcurl4-nss-dev \
                   sqlite3 \
                   libsqlite3-dev \
                   git \
                   make \
                   g++

# systemctl3
COPY init/systemctl3.py /bin/systemctl
COPY init/systemctl3.py /bin/systemctl3.py
COPY init/journalctl3.py /bin/journalctl

# Copy systemd files
COPY ["init/mavlink-router.service", \
      "init/uavcast-camera.service", \
      "init/uavcast-vpn.service", \
      "init/uavcast-web.service", \
      "init/uavcast.service", "/etc/systemd/system/"]

RUN mkdir -p /app/uavcast/data && chown -R uavcast /app/uavcast/data

# Create mavlink directory
RUN mkdir -p /etc/mavlink-router
COPY ["etc/mavlink-router-example.conf", "/etc/mavlink-router/main.conf"]

RUN chmod +x  /bin/systemctl \
              /bin/systemctl3.py \
              /bin/journalctl

# zerotier installation
RUN sudo curl -s https://install.zerotier.com/ | sudo bash

ENV NODE_ENV=development