FROM sinamics/uavcast-base:latest
LABEL maintainer="Bernt Christian Egeland / (aka sinamics)"

WORKDIR /app/uavcast

ENV NPM_CONFIG_PREFIX=/home/uavcast/.npm-global
ENV PATH=$PATH:/home/uavcast/.npm-global/bin

# systemctl3
COPY init/systemctl3.py /bin/systemctl
COPY init/systemctl3.py /bin/systemctl3.py
COPY init/journalctl3.py /bin/journalctl

# Copy systemd files
COPY ["init/mavlink-router.service", \
      "init/uavcast-camera.service", \
      "init/uavcast-vpn.service", \
      "init/uavcast-web.service", \
      "init/uavcast.service", "/etc/systemd/system/"]

RUN mkdir -p /app/uavcast/data && chown -R uavcast /app/uavcast

# Create mavlink directory
RUN mkdir -p /etc/mavlink-router
COPY ["etc/mavlink-router-example.conf", "/etc/mavlink-router/main.conf"]

RUN chmod +x  /bin/systemctl \
              /bin/systemctl3.py \
              /bin/journalctl

RUN sudo touch /var/run/docker.sock
RUN sudo chmod 666 /var/run/docker.sock
RUN sudo chown uavcast:docker /var/run/docker.sock

ENV NODE_ENV=development