FROM sinamics/debian-uavcast-base:latest
LABEL maintainer="Bernt Christian Egeland / uavmatrix.com"

ENV NPM_CONFIG_PREFIX=/home/uavcast/.npm-global
ENV PATH=$PATH:/home/uavcast/.npm-global/bin

ARG USERNAME=uavcast
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# RUN usermod -aG docker $USERNAME

# systemctl3
COPY init/systemctl3.py /bin/systemctl
COPY init/systemctl3.py /bin/systemctl3.py
COPY init/journalctl3.py /bin/journalctl

COPY docker/bin/entrypoint.sh /home/uavcast/etc/

RUN mkdir -p /app/uavcast/data && chown -R uavcast /app/uavcast/data

RUN chmod +x  /bin/systemctl \
              /bin/systemctl3.py \
              /bin/journalctl

# RUN sudo chown -R uavcast /home/uavcast/

ENV NODE_ENV=development