name: ci
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  checkout:
    runs-on: self-hosted
    # Map a step output to a job output
    outputs:
      version: ${{ steps.previoustag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required due to the weg Git works, without it this action won't be able to find any or the correct tags

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 5.0.0 # Optional fallback tag to use when no tag can be found

  submodule:
    runs-on: self-hosted
    needs: checkout
    steps:
      - name: Git Sumbodule Update
        run: |
          git submodule update --init --recursive

  build_gcc:
    runs-on: self-hosted
    needs: submodule
    steps:
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev libjsoncpp-dev libv4l-dev libgstreamer1.0-dev libcurl4-nss-dev sqlite3 libsqlite3-dev
      - name: make binaries
        run: make -C bin/

  build_backend:
    runs-on: self-hosted
    needs: [build_gcc, submodule]
    steps:
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-backend-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: cd backend && npm install
      - name: Build Backend
        run: cd backend && npm run build

  build_frontend:
    runs-on: self-hosted
    needs: [build_gcc, submodule]
    steps:
      - name: Cache frontend modules
        uses: actions/cache@v2
        env:
          cache-name: cache-frontend-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: cd frontend && npm install
      - name: Build frontend
        run: cd frontend && npm run build

  lint_check:
    runs-on: self-hosted
    needs: [build_frontend, build_backend]
    steps:
      - name: backend lint
        run: cd backend && npm run lint
      - name: frontend lint
        run: cd frontend && npm run lint

  build_docker:
    runs-on: self-hosted
    needs: [lint_check]
    steps:
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:master
            network=host
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.publish
          platforms: linux/arm/v7,linux/arm64
          push: true
          tags: sinamics/uavcast:${{ needs.checkout.outputs.version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
