name: Pull Request

on: 
  pull_request:
  workflow_dispatch:

jobs:
  web_lint:
    name: Web - Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14.x
      - run: npm install
        working-directory: ./backend
      - name: Lint
        run: npm run lint:cmd
        working-directory: ./backend

      - run: npm install
        working-directory: ./frontend
      - name: Lint
        run: npm run lint:cmd
        working-directory: ./frontend

  web_build:
    name: Web - Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14.x
      - run: npm install
        working-directory: ./backend
      - name: Build
        run: npm run build
        working-directory: ./backend

      - run: npm install
        working-directory: ./frontend
      - name: Build
        run: npm run build
        working-directory: ./frontend
  # web_test:
  #   name: Web - Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - uses: actions/setup-node@master
  #       with:
  #         node-version: 14.x
  #     - run: npm install
  #       working-directory: ./web
  #     - name: Test
  #       run: npm run test
  #       working-directory: ./web